apiVersion: v1
kind: ConfigMap
metadata:
  name: nil-values-bug
data:
  item-count: "{{ len .Values.items }}"
  item-keys: "{{ keys .Values.items | sortAlpha | join "," }}"
  filter-is-truthy: {{ if .Values.filter }}"yes"{{ else }}"no"{{ end }}
